name: Build page
on:
  push:
    branches:
      - main
  schedule:
     - cron:  '4 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: > 
          sudo apt-get update
          && sudo apt-get install -y python3-pip
          && pip3 install -r requirements.txt
      - name: Build
        run: >
          jupyter nbconvert --ExecutePreprocessor.kernel_name=python3 --execute --to html Covid.ipynb
          && mkdir public
          && mv Covid.html public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
