name: Build page
on:
  push:
    branches:
      - main
  schedule:
     - cron:  '4 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Build
        run: |
          jupyter nbconvert --execute Covid.ipynb
          mkdir public
          mv *.html public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
